// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "converter.py",
        "revision": "ee81dcb8433230d3a4047731264476ef"
    },
    {
        "url": "for_translation.csv",
        "revision": "f9dee3c60eb30db54b3e998a0466e90b"
    },
    {
        "url": "index.html",
        "revision": "51bd933d262fa3511f16d0a7c0cda774"
    },
    {
        "url": "index2.html",
        "revision": "219ab94b932e4a92e4321dc09226cf4a"
    },
    {
        "url": "index3.html",
        "revision": "3034e8150eceb972514175f7901bf939"
    },
    {
        "url": "listmodel.py",
        "revision": "8c87f76802bd005ffe37645ac1b602a3"
    },
    {
        "url": "mcqs_bilingual.json",
        "revision": "3ea3fc0ce981654f27f21c1992d4e364"
    },
    {
        "url": "mcqs_bilingual_sequential2.json",
        "revision": "6c1b6119499fc08461d9ed98be89bd44"
    },
    {
        "url": "mcqs_data.json",
        "revision": "41758a02ffd776e4ca6106abf59c34b0"
    },
    {
        "url": "mcqs_urdu.json",
        "revision": "d693c63892967cc1d321b728aa936a02"
    },
    {
        "url": "merger.py",
        "revision": "a64de004fcc2aba3326e6900d62ed0ff"
    },
    {
        "url": "merger2.py",
        "revision": "27c44da975b5fe41b6d0ac1337ab32fd"
    },
    {
        "url": "my read for converte,py.txt",
        "revision": "63aa2737d64f8207643a6de0a9d8d212"
    },
    {
        "url": "offline.html",
        "revision": "7656c61e25225c4fcc77cb000be6d527"
    },
    {
        "url": "pakmcqs_all_questionsa.txt",
        "revision": "4dae7d013f3b9389e7e5dd74dd96eaf2"
    },
    {
        "url": "pakmcqs_all_questions_fast.txt",
        "revision": "b3d681d564fe30a596ac373f88ce3c20"
    },
    {
        "url": "PakMCQs_App.html",
        "revision": "28f6143f4dc4bfc55614ed13a940c512"
    },
    {
        "url": "PakMCQs_Formatted.html",
        "revision": "bec629e8ce03814f51b9cac30ffcd1b4"
    },
    {
        "url": "PakMCQs_Formatted.htm_",
        "revision": "fecb5228f8327541f329b03e7e1222f4"
    },
    {
        "url": "PakMCQs_Formatted_from_TXT.docx",
        "revision": "976ce72d75b8fb53e4984f636fb15e2b"
    },
    {
        "url": "PakMCQs_Study_App.html",
        "revision": "c9506d92dd8f14e5604c65289316b8ea"
    },
    {
        "url": "readme.md",
        "revision": "8afdd1893905f4d415f7535acb4ffd95"
    },
    {
        "url": "rewrittenqs.py",
        "revision": "fdfe8c45ffe6e3bd4c2330546c377522"
    },
    {
        "url": "rewritten_mcqs_and_answers.json",
        "revision": "9b63e36a59ef8575626605f1f7c40bfe"
    },
    {
        "url": "rewritten_mcqs_no_ai.json",
        "revision": "2fabaed0bade41a0355fc22d3d9c3651"
    },
    {
        "url": "rurn.py",
        "revision": "b32ed9a5f560084b783262e07ae1868f"
    },
    {
        "url": "scrap.py",
        "revision": "2646c548b9e4bfe69daf63b645f4daaf"
    },
    {
        "url": "tohtml.py",
        "revision": "e9a3ccf7351303af60f6be7782f2dd8c"
    },
    {
        "url": "tohtml2.py",
        "revision": "07b0406747905991591e475a2870cc5e"
    },
    {
        "url": "toword.py",
        "revision": "4b656b8c62964ae73886d7bd29b5caf5"
    },
    {
        "url": "translated_from_sheets.csv",
        "revision": "0d5badb00984a172887ce77e6add9288"
    },
    {
        "url": "urrewrittenqs.py",
        "revision": "3f4e77e9753c65234a4cdfc0a055ef9a"
    },
    {
        "url": "PakMCQs_Formatted_files/colorschememapping.xm_",
        "revision": "6b7a472a22fbdbff4b2b08ddb4f43735"
    },
    {
        "url": "PakMCQs_Formatted_files/themedata.thm_",
        "revision": "2cae7505f2860beb9f284cd2ddb9057b"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}